sudo: false
language: python

python:
- 2.7
- 3.5
- 3.6

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n bcolz_env python=$TRAVIS_PYTHON_VERSION
          numpy pandas cython nose coverage numexpr dask
  - source activate bcolz_env
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then conda install mock; fi

  # Build bcolz
  - python setup.py build_ext --inplace

script:
  - nosetests --with-coverage --cover-package bcolz bcolz/tests/test_*.py

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then bash ./coveralls_after_test_succes.sh; fi

notifications:
  email: false
