[project]
requires-python = ">=3.7"

[build-system]
# Minimum requirements for the build system to execute.
requires = [
    "setuptools>=18.0",
    "setuptools_scm[toml]>=3.4",
    "Cython>=0.22",
    "numpy==1.16.5; python_version=='3.7'",
    "numpy==1.17.3; python_version=='3.8'",
    "numpy; python_version>='3.9'",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "bcolz/version.py"
version_scheme = 'guess-next-dev'
local_scheme = 'dirty-tag'
